/**
 * Library readings, verbatim from the client document set.
 *
 * Mandatory Policies 2, 3, 4, 5 and 10 — the participant-facing ones — from
 * the TMG180 Mandatory Policies Governance Controlled Manual v1.0 (21 June
 * 2026). Each is the policy's own text in its own order. Two things are left
 * out of each and nowhere else: the "GOVERNANCE CONTROL PURPOSE / LEGAL AND
 * REGULATORY BASIS" header cells (carried once as the opening lines) and the
 * closing "Audit and Governance Controls" table, which is a control record for
 * auditors, not reading.
 *
 * The manual's own status is "Working Governance Draft — requires legal
 * review, terminology review and source-currency review before formal
 * adoption". That is said on every one of these readings (see
 * PARTICIPANT_READING_DRAFT_NOTE in participantLibrary.js) and the text is
 * not touched to pre-empt it — a participant reading a draft is told it is
 * one, not handed a quiet rewrite.
 *
 * Then the evidence readings: how the Longitudinal Evidence Templates v2.0
 * work together, the Monthly Relational Longitudinal Snapshot's own purpose,
 * the Goal Mapping examples (Master Document Map #9, DISPLAY), the AI
 * Governance Register and the Governance Architecture — all verbatim.
 */

const h2 = (text) => ({ kind: 'h2', text });
const p = (text) => ({ kind: 'p', text });
const list = (items) => ({ kind: 'list', items });

export const POLICY_2_BODY = [
  p('Provide safe, non-retaliatory and proportionate pathways for feedback and complaints without turning every concern into punishment.'),
  p('Legal and regulatory basis: NDIS Code of Conduct; NDIS Act 2013 choice and control principles; Privacy Act 1988; consumer protection principles; digital platform safeguarding expectations.'),
  h2('Purpose of this Policy'),
  p('The purpose of this policy is to explain how complaints, concerns, and feedback are received and responded to within TMG180 Governance Administration in a way that is respectful, transparent, trauma-informed, and consistent with legislative obligations.'),
  p('This policy recognises that feedback and complaints are a normal part of working in complex human systems It exists to provide safe pathways for raising concerns without fear, blame, or retaliation, while ensuring serious issues are addressed appropriately.'),
  p('TMG180 Governance Administration is part of a digital platform and not a NDIS service provider This policy does not replace service delivery complaint processes between workers and participants.'),
  h2('Scope'),
  p('This policy applies to:'),
  list(['Participants using TMG180 180 digital platform', 'Independent workers operating through the platform', 'Platform administrators, in relation to governance and platform safety only']),
  p('This policy does not apply to:'),
  list(['employment disputes', 'clinical supervision', 'provider level complaint handling']),
  h2('Definitions'),
  p('Complaint — An expression of dissatisfaction, concern, or discomfort about conduct, safety, communication, or platform use.'),
  p('Feedback — Information provided with the intention of improving understanding, relationships, or systems.'),
  p('Platform Related Complaint — A complaint about the operation of TMG180 180, including platform conduct, policies, verification processes, or safety mechanisms.'),
  p('Service Related Complaint — A complaint about support delivery, which is primarily managed between the participant and the independent worker.'),
  h2('Legal and Regulatory Basis'),
  p('This policy aligns with and is informed by:'),
  list(['NDIS Code of Conduct (including respect, integrity, and safety)', 'NDIS Act 2013 principles of choice and control', 'Privacy Act 1988', 'Consumer protection principles', 'Digital platform safeguarding expectations']),
  h2('Principles Guiding Complaints and Feedback'),
  p('TMG180 Governance Administration operate on the principle that:'),
  list(['raising concerns is not a sign of failure', 'people are more likely to act ethically when they feel safe to speak', 'complaints should be handled calmly and proportionately', 'not all concerns require punitive action', 'serious matters require clear escalation', 'human context matters']),
  p('TMG180 administrators listen first, understand the situation, and respond in a way that supports safety and learning rather than blame.'),
  h2('Making a Complaint or Providing Feedback'),
  p('Participants and workers are expected to raise:'),
  list(['concerns about safety', 'boundary issues', 'communication difficulties', 'platform processes', 'policy clarity', 'conduct that feels inappropriate or uncomfortable']),
  p('Feedback or complaints may be raised:'),
  list(['through the platform', 'in writing', 'verbally where appropriate']),
  p('No one is required to use legal language or formal wording.'),
  h2('Response'),
  p('TMG180 Governance Administration will respond to complaints that relate to:'),
  list(['platform governance', 'worker conduct that presents safety or ethical concerns', 'misuse of the platform', 'serious boundary breaches', 'failure to meet platform participation conditions', 'issues affecting platform integrity or trust']),
  p('The platform does not manage day-to-day service delivery complaints unless there is a risk to safety or serious misconduct.'),
  h2('How Complaints Are Handled'),
  p('When a complaint is received, TMG180 Governance Administration will:'),
  list(['acknowledge receipt of the concern', 'seek clarification where needed', 'assess whether the issue is platform related or service related', 'respond proportionately', 'provide guidance or clarification', 'take steps to protect safety', 'refer matters to external bodies where required']),
  p('Responses are guided by fairness, transparency, and respect for all parties involved.'),
  p('Not every complaint leads to disciplinary action Some lead to clarification, learning, or improved understanding.'),
  h2('Serious Concerns and Escalation'),
  p('Where a complaint involves:'),
  list(['serious safety risks', 'alleged abuse or neglect', 'serious misconduct', 'unlawful behaviour']),
  p('TMG180 Governance Administration will :'),
  list(['suspend platform access', 'notify appropriate authorities', 'support referral to external regulators']),
  p('Participants and workers are always free to escalate concerns directly to:'),
  list(['the NDIS Quality and Safeguards Commission', 'police or emergency services', 'consumer or human rights bodies']),
  h2('Protection From Retaliation'),
  p('TMG180 Governance Administration does not tolerate retaliation against anyone who raises concerns in good faith.'),
  p('Raising a complaint or providing feedback will not, on its own, result in negative consequences.'),
  h2('Privacy and Confidentiality'),
  p('Complaints are handled with respect for privacy.'),
  p('Information is shared only where necessary to:'),
  list(['understand the concern', 'respond appropriately', 'meet legal obligations']),
  p('Completed service records and documentation remain under worker control and are not accessed by the platform.'),
  h2('Platform Limits'),
  p('Tmg180 180:'),
  list(['does not act as a mediator for service delivery disputes', 'does not adjudicate clinical matters', 'does not replace formal regulatory processes', 'does not supervise workers']),
  p('The platform’s role is governance, not management.'),
  h2('Review of This Policy'),
  p('This policy is reviewed regularly to ensure it remains effective, lawful, and aligned with best practice.'),
  h2('Contact'),
  p('Questions or concerns about this policy may be raised through TMG180 180 administrators’ governance contact pathways.'),
];

export const POLICY_3_BODY = [
  p('Separate platform-level incident governance from worker-controlled service-level incident responsibilities while preserving escalation options.'),
  p('Legal and regulatory basis: NDIS Code of Conduct; NDIS Act 2013 dignity, choice and control principles; WHS principles; Privacy Act 1988; digital platform safeguarding expectations.'),
  h2('Purpose of this Policy'),
  p('The purpose of this policy is to explain how incidents are recognised, responded to, documented, and escalated by TMG180 Governance Administration in a way that supports safety, transparency, and ethical practice for both participants and workers.'),
  p('This policy acknowledges that incidents can arise in complex, human situations, even where people are acting in good faith It exists to provide clear, supportive pathways for responding to concerns without blame, fear, or unrealistic expectations.'),
  p('TMG180 Governance Administration oversee a digital platform and is not a NDIS service provider Independent workers remain responsible for service delivery and for managing incidents that arise within their own practice.'),
  h2('Scope'),
  p('This policy applies to:'),
  list(['Participants using TMG180 180 digital platform', 'Independent workers operating through the platform', 'Platform administrators, in relation to governance, safeguarding, and platform integrity']),
  p('This policy does not apply to:'),
  list(['clinical incident review', 'provider level incident management', 'employment based disciplinary processes']),
  h2('Definitions'),
  p('Incident — Any event, situation, or pattern of behaviour that raises concern about safety, wellbeing, boundaries, or ethical practice This may include physical, emotional, relational, environmental, or digital safety issues.'),
  p('Platform Level Incident — An incident that relates to platform governance, misuse of the platform, worker eligibility, serious boundary breaches, or conduct that may affect the safety or integrity of the platform.'),
  p('Service Level Incident — An incident that occurs during support delivery and is primarily managed by the independent worker as part of their professional responsibilities.'),
  h2('Legal and Regulatory Basis'),
  p('This policy aligns with and is informed by:'),
  list(['NDIS Code of Conduct, including obligations to act safely and with integrity', 'NDIS Act 2013 principles of dignity, choice, and control', 'Work Health and Safety principles, including psychosocial safety', 'Privacy Act 1988', 'Digital platform safeguarding expectations']),
  h2('Principles Guiding Incident Management'),
  p('TMG180 Governance Administration operates on the principle that:'),
  list(['safety includes physical, emotional, relational, and psychological wellbeing', 'incidents are not always the result of wrongdoing', 'early identification reduces harm', 'people are more likely to act ethically when they feel safe to speak', 'context matters', 'proportionate responses are essential']),
  p('What this means at TMG180: This policy is designed to support learning, safety, and accountability, not to punish people for being human.'),
  h2('Recognising Incidents'),
  p('Incidents may be identified by participants or workers and may include, but are not limited to:'),
  list(['physical injury or risk of harm', 'emotional distress or trauma activation', 'boundary crossings or role confusion', 'aggressive, threatening, or intimidating behaviour', 'unsafe or unstable environments', 'significant breakdowns in communication', 'safeguarding concerns', 'misuse of the platform', 'digital or privacy related concerns']),
  p('Participants and workers are expected to trust their judgement when something feels unsafe, confusing, or not right.'),
  h2('Responsibilities in Relation to Incidents'),
  p('Participant and Worker Responsibilities — Participants and workers are expected to:'),
  list(['raise concerns early rather than waiting for situations to escalate', 'prioritise safety for themselves and others', 'communicate concerns in a way that feels safe and manageable', 'seek support or clarification when unsure how to respond', 'engage in discussion where appropriate and safe to do so']),
  p('Participants and workers are not expected to handle situations beyond their capacity, role, or sense of safety.'),
  p('What this means at TMG180: No one is expected to cope alone or to have all the answers in the moment.'),
  p('Worker Responsibilities in Service Level Incidents — Independent workers remain responsible for:'),
  list(['taking reasonable steps to ensure immediate safety', 'pausing, adjusting, or leaving situations that feel unsafe', 'seeking emergency assistance where required', 'documenting incidents privately using WCPS or another secure system', 'reflecting on what occurred and adjusting practice where appropriate']),
  p('Workers are expected to use judgement and discretion rather than rigid rules.'),
  h2('Platform Responsibilities'),
  p('TMG180 Governance Administration will only respond to platform level incidents by:'),
  list(['acknowledging reports from participants or workers', 'assessing whether concerns relate to platform governance or service delivery', 'taking proportionate steps to protect safety and platform integrity', 'providing guidance or clarification where appropriate', 'suspending or removing access where serious risk is identified', 'referring matters to external authorities when legally required']),
  p('The platform does not:'),
  list(['manage service level incident responses', 'conduct clinical investigations', 'access or review service documentation', 'replace statutory reporting obligations']),
  h2('Speaking Up and Raising Concerns'),
  p('Speaking up, whether by a participant or a worker, is recognised as responsible and protective, not as causing trouble.'),
  p('TMG180 Governance Administration recognizes that safe systems depend on people feeling able to raise concerns without fear of blame, retaliation, or dismissal.'),
  p('Concerns raised in good faith by participants or workers are treated with respect and taken seriously raising an issue does not, on its own, imply fault or wrongdoing.'),
  p('Safety grows when people feel able to speak honestly, regardless of role.'),
  h2('Escalation and External Reporting'),
  p('Where an incident involves:'),
  list(['serious harm or risk of harm', 'alleged abuse, neglect, or exploitation', 'criminal behaviour', 'serious breaches of the NDIS Code of Conduct']),
  p('Participants and workers may escalate concerns to appropriate external bodies, including:'),
  list(['the NDIS Quality and Safeguards Commission', 'police or emergency services', 'relevant safeguarding or oversight agencies']),
  p('The platform may also make reports where legally required.'),
  h2('Documentation and Privacy'),
  p('Incident related documentation created by workers:'),
  list(['remains under worker control', 'is stored privately using WCPS or another secure system', 'is not accessed by TMG180 180']),
  p('The platform records only information necessary to manage platform safety and governance.'),
  h2('Response to Patterns or Ongoing Risk'),
  p('Where patterns of concern emerge, TMG180 Governance Administration will:'),
  list(['seek clarification', 'provide guidance', 'recommend changes to platform participation', 'suspend or remove access to protect safety']),
  p('Actions are proportionate and focused on prevention and integrity rather than punishment.'),
  h2('Review of this Policy'),
  p('This policy is reviewed regularly to reflect legislative change, regulatory guidance, and learning from real world practice.'),
  h2('Contact'),
  p('Questions or concerns about this policy may be raised through TMG180 180 administrators’ governance contact pathways.'),
];

export const POLICY_4_BODY = [
  p('Protect consent, participant autonomy, privacy and information minimisation across participant-owned portal records and worker-controlled records.'),
  p('Legal and regulatory basis: Privacy Act 1988 and APPs; NDIS Act 2013 choice and control principles; NDIS Code of Conduct; human rights principles; digital platform governance expectations.'),
  h2('Purpose of this Policy'),
  p('The purpose of this policy is to set out how consent is obtained, recorded, respected, and withdrawn across TMG180 Governance Administration digital platform, and how information is handled in a lawful, ethical, and human centered way.'),
  h2('Scope'),
  p('This policy applies to:'),
  list(['Independent workers operating to TMG180 Governance Administration', 'Participants and their authorised representatives', 'Platform administrators in relation to governance and oversight functions']),
  p('This policy does not apply to clinical governance, service delivery supervision, or provider level record keeping, as these functions are not performed by TMG180 180.'),
  h2('Definitions'),
  p('Consent — Freely given, informed, specific, and voluntary agreement to an action or decision, which can be withdrawn at any time.'),
  p('Information — Any personal, sensitive, or service related information relating to a participant or worker.'),
  p('WCPS (Worker Controlled Private Storage) — A secure, encrypted storage environment within a worker’s dashboard that is accessible only by the worker and not by TMG180 Governance Administration.'),
  h2('Legal and Regulatory Basis'),
  p('This policy aligns with and is informed by:'),
  list(['Privacy Act 1988 (Cth) and Australian Privacy Principles', 'NDIS Act 2013, including principles of choice and control', 'NDIS Code of Conduct, including respect for rights, informed decision-making, and privacy', 'Human rights principles relevant to disability and autonomy', 'Digital platform governance expectations']),
  h2('Principles of Consent'),
  p('Consent under TMG180 Governance Administration must be:'),
  list(['Informed', 'Voluntary', 'Specific to the task or information', 'Ongoing', 'Able to be withdrawn without penalty']),
  p('Workers are expected to ensure participants understand:'),
  list(['What information is being recorded or shared', 'Why it is being recorded or shared', 'How it will be used', 'Who will have access', 'Their right to say no or change their mind']),
  p('What this means at TMG180: Consent should feel safe and respectful Workers are expected to use plain, human language and to check in regularly, especially where capacity fluctuates or trauma is present.'),
  h2('Obtaining and Withdrawing Consent'),
  p('Independent workers are responsible for:'),
  list(['Seeking consent before recording information', 'Rechecking consent when circumstances change', 'Respecting withdrawal of consent immediately', 'Adjusting documentation and practice accordingly']),
  p('Consent must never be assumed, implied, or coerced.'),
  p('Participants may withdraw consent:'),
  list(['For specific information', 'For certain types of documentation', 'For collaboration or sharing', 'For ongoing support arrangements']),
  p('Withdrawal of consent must not result in pressure, judgement, or reduced respect.'),
  h2('Information Handling Responsibilities'),
  p('What the Platform Does:'),
  list(['Stores worker verification and compliance documents only', 'Maintains governance level metadata for platform safety']),
  p('What the Platform Does Not Do — TMG180 Governance Administration does not:'),
  list(['access participant records', 'Access support documentation', 'Review service notes', 'Monitor worker documentation', 'Direct what is recorded']),
  p('This separation preserves digital platform status and protects participant privacy.'),
  p('Worker Responsibilities — Independent workers are responsible for:'),
  list(['Recording only information that is necessary and relevant', 'Storing service records securely using WCPS or an equivalent secure system', 'Sharing records directly with participants upon request', 'Obtaining consent before sharing information with any third party', 'Ensuring documentation is factual, respectful, and nonjudgemental', 'Protecting information from unauthorised access']),
  h2('Participant Rights'),
  p('Participants have the right to and are encouraged to:'),
  list(['Create a personal portal, own and have independent access to their own information and documents.', 'Have input to their case notes in their own words.', 'Understand what information is recorded', 'Request access to their records directly from the worker', 'Request corrections or clarifications', 'Decline recording of certain information', 'Withdraw consent at any time', 'Be supported without pressure or coercion.']),
  h2('Complaints and Concerns'),
  p('Concerns about consent or information handling may be raised through TMG180 180 governance process.'),
  p('Where required, participants and workers may also escalate concerns to external bodies, including the NDIS Quality and Safeguards Commission or privacy regulators.'),
  h2('Breach Management'),
  p('If a breach of consent or information handling occurs:'),
  list(['Workers must take immediate steps to reduce harm', 'Serious breaches must be reported through appropriate regulatory channels', 'Platform level breaches will be managed in accordance with the platform’s incident and cybersecurity policies']),
  h2('Review of this Policy'),
  p('This policy is reviewed regularly and updated to reflect legislative changes, regulatory guidance, and emerging best practice.'),
  p('Questions about this policy may be directed to TMG180 Governance Administration via the platform.'),
];

export const POLICY_5_BODY = [
  p('Give participants, families, agencies and the public clear information about what TMG180 is, what it is not, and what rights and limits apply.'),
  p('Legal and regulatory basis: NDIS Act 2013 participant rights and choice/control principles; NDIS Code of Conduct; privacy, consumer and public transparency expectations.'),
  p('This statement explains how the platform works for participants, families, carers, agencies, and members of the publicity sets out rights, safeguards, and transparency principles It does not create contractual obligations for participants or the public.'),
  h2('Purpose of this Statement'),
  p('The purpose of this statement is to provide clear, accessible information about how The Middle Ground 180 governance administration operates oversight of the digital platform,, what participants and the public can expect when using the platform, and how rights, choice, and transparency are protected.'),
  p('This statement recognises that people engaging with disability and aged care systems are often given unclear or conflicting information It exists to reduce confusion and support informed, voluntary engagement.'),
  h2('Who This Statement Applies To'),
  p('This statement applies to:'),
  list(['Participants using TMG180 180 digital platform to find or engage independent workers', 'Family members, carers, and authorised representatives', 'Agencies or providers seeking information about collaboration', 'Members of the public accessing platform information']),
  p('This statement does not apply to:'),
  list(['worker subscription terms', 'service agreements between workers and participants', 'employment or provider contracts']),
  h2('What TMG180 180 Is'),
  p('TMG180 180 is:'),
  list(['a digital platform', 'a connection and information space', 'a governance and safety framework', 'a place where participants can view verified worker profiles']),
  p('TMG180 180 is not:'),
  list(['a service provider', 'an employer', 'a support coordinator', 'a case manager', 'a holder of participant case notes', 'a controller of service delivery']),
  p('What this means at TMG180: Participants are not signing up to a provider Participants can create a free portal account to access their own portal This account based access supports privacy, consent controls, and cybersecurity Participants remain in control of who they engage and how.'),
  h2('Costs and Charges'),
  p('Participants and members of the public are not charged to use TMG180 180.'),
  p('Any financial arrangements are made directly between the participant and the independent worker.'),
  h2('Choice, Control, and Voluntary Engagement'),
  p('Participants retain full choice and control when using TMG180 Governance Administration digital ecosystem.'),
  p('This includes the right to:'),
  list(['choose which workers to contact', 'decide whether to engage a worker', 'change workers at any time', 'pause or stop support', 'decide what support looks like', 'say no without explanation']),
  p('Use of the platform is voluntary No one is required to remain engaged.'),
  h2('Independent Workers'),
  p('Workers listed on TMG180 180 digital ecosystem platform as independent business operators.'),
  p('This means:'),
  list(['they are not employed by TMG180', 'they manage their own availability and rates', 'they enter service agreements directly with participants', 'they are responsible for their own documentation and compliance']),
  p('The platform verifies worker eligibility and provides governance safeguards but does not supervise service delivery.'),
  h2('Privacy and Information'),
  p('TMG180 Governance Administration respects privacy and minimises data collection.'),
  p('The platform:'),
  list(['does not access worker-controlled narrative case notes or service records stored in WCPS', 'does not monitor service interactions', 'stores only platform governance data and participant owned snapshot records (intake/check-ins/support event logs/monthly snapshot exports) where the participant chooses to use the portal and gives consent']),
  p('Worker narrative notes and full service records remain under worker control and are shared directly with the participant if requested.'),
  p('Participants have the right and are encouraged to:'),
  list(['understand how information is used', 'ask questions about documentation', 'review records from the worker', 'withdraw consent for information sharing']),
  h2('Speaking Up and Raising Concerns'),
  p('Participants, workers, and members of the public are encouraged to speak up if something feels unsafe, confusing, or concerning.'),
  p('Speaking up is recognised as responsible and protective, not as causing trouble.'),
  p('Concerns raised in good faith are treated with respect and taken seriously.'),
  h2('Respectful Engagement by Agencies and Providers'),
  p('TMG180 Governance Administration recognises that agencies or providers may wish to engage workers listed on the platform for employment, subcontracting, or collaboration.'),
  p('Workers are not restricted from engaging with agencies or providers.'),
  p('To support transparency and worker choice, the platform encourages agencies and providers to:'),
  list(['contact TMG180 Governance Administration rather than approaching individual workers directly, unless a worker has clearly indicated openness to such contact', 'engage through respectful and transparent processes', 'avoid unsolicited or repeated approaches to workers who have not opted in']),
  p('The platform maintains a list of workers who have chosen to indicate that they are open to agency or provider engagement This allows collaboration to occur without pressure, misrepresentation, or disruption to workers who are choosing to operate independently.'),
  h2('Administrative Facilitation Fee'),
  p('Where TMG180 Governance Administration facilitates an introduction or connection between an agency or provider and a worker listed on the platform, the platform may charge a small administrative facilitation fee.'),
  p('This fee reflects work already undertaken by the platform, including:'),
  list(['verification of worker credentials and eligibility', 'confirmation of relevant checks and insurances', 'maintenance of accurate and transparent worker profiles', 'provision of governance and safeguarding frameworks', 'facilitation of ethical, consent based engagement']),
  p('The facilitation fee:'),
  list(['is disclosed transparently in advance', 'is charged to the agency or provider, not the worker', 'is not deducted from worker earnings', 'does not restrict worker independence or choice', 'is not a commission on labour']),
  p('The platform is paid for governance and facilitation work, not for controlling people or taking a cut of their labour.'),
  h2('Limits of the Platform'),
  p('TMG180 180 digital platform does not:'),
  list(['control service delivery', 'make decisions about funding', 'manage support plans', 'replace advocacy', 'adjudicate disputes between workers and participants']),
  p('The platform exists to support connection, transparency, and ethical engagement, not to control outcomes.'),
  h2('External Options'),
  p('Participants and members of the public may contact external bodies at any time, including:'),
  list(['the NDIS Quality and Safeguards Commission', 'aged care or disability oversight bodies', 'advocacy organisations', 'emergency services if immediate risk exists']),
  p('TMG180 Governance Administration does not discourage or restrict external complaints.'),
  h2('Review of This Statement'),
  p('This statement is reviewed regularly to reflect legislative change, regulatory guidance, and feedback from lived experience.'),
  h2('Contact'),
  p('Questions about this statement may be directed to TMG180 Governance Administration via the platform.'),
];

export const POLICY_10_BODY = [
  p('Affirm non-discrimination, equity, cultural safety, inclusion and response pathways for bias or discriminatory conduct.'),
  p('Legal and regulatory basis: Disability Discrimination Act 1992; Sex Discrimination Act 1984; NDIS Code of Conduct; Australian human rights law; social model of disability and intersectional practice principles.'),
  h2('Purpose'),
  p('This policy affirms TMG180 180’s governance administrations commitment to non-discrimination, dignity, and fair treatment for all participants, workers, and community members engaging with the platform It aligns with the principles of the Disability Discrimination Act 1992, the Sex Discrimination Act 1984, the NDIS Code of Conduct, and Australian human rights law.'),
  h2('Scope'),
  p('This policy applies to all users of TMG180 180 digital platform It covers engagement, communication, content, and participation in peer pods, shared resources, training, and governance activities.'),
  h2('Legal and Ethical Foundations'),
  p('TMG180 administrators are committed to upholding the rights of individuals to participate free from discrimination based on:'),
  list(['Disability', 'Gender or gender identity', 'Sexuality', 'Race, cultural background, or language', 'Age', 'Religion or belief', 'Health status or mental health diagnosis', 'Any other status protected by law']),
  p('This policy is framed within the social model of disability and acknowledges intersecting experiences of disadvantage.'),
  h2('TMG180 Governance Commitments'),
  list([
    'will ensure platform content, structures, and communications do not discriminate or exclude.',
    'will provide a mechanism to report discriminatory behaviour, bias, or harm experienced in digital spaces connected to TMG180.',
    'will support inclusive practices in all modules, governance processes, and worker resources.',
    'will recognise diverse experiences of gender, neurodivergence, trauma, and identity and embed that recognition in platform guidance and templates.',
  ]),
  p('TMG180 Governance will not tolerate vilification, harassment, or language that causes harm to any group or individual.'),
  h2('Inclusive Participation'),
  p('TMG180 Governance welcome and support all people to provide feedback about the platform, including:'),
  list(['Governance', 'Peer Led training', 'Policy development']),
  p('TMG180 Governance do not impose expectations of disclosure'),
  p('Privacy and personal safety remain core values.'),
  h2('Response to Discrimination'),
  p('Where discriminatory conduct is reported, TMG180 Governance Administration will:'),
  list(['Facilitate dialogue where safe and appropriate', 'Offer restorative engagement where agreed', 'Pause or remove access to maintain platform safety', 'Escalate repeated harm to appropriate authorities (if consented to and/or required by law)']),
  h2('Alignment with Internal Practice Policies'),
  p('This policy is integrated with internal ethical practice policies including:'),
  list(['Gender and Sexuality Inclusion', 'Bias and Assumption Awareness', 'Labels and Diagnosis Position', 'Harm Minimisation and Relational Safety']),
  h2('Feedback and Review'),
  p('TMG180 Governance invite community feedback on the accessibility, clarity, and lived experience alignment of this policy 180 Governance are committed to ongoing review and codesign.'),
];

/** Longitudinal Evidence Templates v2.0 — the front matter and the tone rules, verbatim. */
export const EVIDENCE_TEMPLATES_BODY = [
  h2('How These Templates Work'),
  p('These three templates work together to build participant-owned longitudinal evidence over time. They sit inside the TMG180 platform and connect automatically — but they can also be used as standalone documents.'),
  p('Template A — Support Event Log (Worker)'),
  p('Completed by the worker after each visit. Takes 30–60 seconds.'),
  p('Captures what support happened, what it helped with, and how the participant was today.'),
  p('Template B — Participant Check-in'),
  p('Completed by the participant — weekly, after a support period, or whenever they choose.'),
  p('Captures their own experience in their own words.'),
  p('Template C — Monthly Snapshot Summary'),
  p('Generated from Template A and B logs each month.'),
  p('Reviewed and approved by the participant before it is locked.'),
  p('This becomes the exportable evidence document for assessments.'),
  h2('Tone rules — non-negotiable'),
  list([
    'Use neutral, non-shaming language at all times',
    'Capacity can fluctuate — a harder week does not mean going backwards',
    'A lower rating is not a failure — it is information',
    'Improvements reflect supports working, not removal of impairment',
    'Worker narrative notes remain confidential — only structured tags are shared',
  ]),
  h2('Template A — Support Event Log'),
  p('Purpose: Capture the essentials of what support happened, what it helped with, and what changed today.'),
  p('Worker narrative notes remain private. Only structured tags and micro-blocks are shared with the participant record.'),
  p('Append-only: once submitted, entries cannot be changed — only addenda added.'),
  h2('Template B — Participant Check-in'),
  p('Purpose: Capture your own experience in your own words.'),
  p('This is your record. It sits alongside the worker log to build a complete picture.'),
  p('There are no right or wrong answers — what matters is what is true for you.'),
  p('Takes 30–60 seconds. You can do more if you want to.'),
  h2('Template C — Monthly Participant Snapshot Summary'),
  p('Purpose: Produce a participant-approved snapshot for NDIS assessments.'),
  p('What happened over time, what support changed, and what needs remain — without shame.'),
  p('This document is append-only. Once approved, it is locked.'),
  p('Corrections or additions are made as addenda — previous entries are never deleted.'),
  p('This document can be exported as a PDF and shared with planners, LACs, or coordinators.'),
  h2('Export and Sharing'),
  p('Once approved, this snapshot can be exported as a PDF and shared with:'),
  list([
    'NDIS planner or LAC — for plan review or reassessment',
    'Support coordinator — for coordination of supports',
    'Allied health professional — for clinical context',
    'Tribunal or review process — as supporting evidence',
    'Kept private — participant record only',
  ]),
  p('Sharing requires explicit participant consent.'),
  p('The participant controls who receives this document.'),
  p('TMG180 cannot share this document without participant approval.'),
];

/** Monthly Relational Longitudinal Snapshot — its Purpose and non-linear statement, verbatim. */
export const MONTHLY_SNAPSHOT_PURPOSE_BODY = [
  h2('Purpose'),
  p('The TMG180 Monthly Relational Longitudinal Snapshot is designed to create a clearer picture over time of:'),
  list([
    'how support is affecting everyday life',
    'what has become more manageable or sustainable',
    'what continues to create barriers',
    'what support is helping',
    'how capacity fluctuates',
    'and what recovery and participation are actually costing the participant over time',
  ]),
  p('This summary is not intended to:'),
  list(['judge progress,', 'measure worth,', 'or reduce people to symptoms or compliance outcomes.']),
  p('The purpose is to help:'),
  list([
    'preserve participant voice',
    'build longitudinal understanding',
    'reduce repeated re-explaining',
    'support reassessment evidence',
    'and demonstrate the relationship between support and sustainable participation over time.',
  ]),
  p('This is a participant-owned summary.'),
  p('A harder month does not mean failure.'),
  p('Fluctuation does not automatically mean regression.'),
  p('Improvement with support reflects support working — not removal of impairment.'),
  h2('Non-Linear Functioning Statement'),
  p('Capacity can fluctuate.'),
  p('A harder period does not automatically mean regression.'),
  p('Improvement with support reflects support working.'),
  p('Many participants experience:'),
  list([
    'fluctuating capacity,',
    'changing recovery needs,',
    'varying stress tolerance,',
    'and periods of increased support need depending on health, environment, stress, burnout, sensory load, or life circumstances.',
  ]),
  p('This is consistent with many psychosocial, neurodivergent, trauma-related, chronic illness, and invisible disability experiences.'),
  p('Suggested longitudinal wording:'),
  p('“Capacity varied across the month in line with non-linear functioning patterns. Participation improved with appropriate support scaffolding, pacing, and relational support. Improvements reflected support effectiveness and reduced recovery cost rather than removal of underlying impairment.”'),
];

/** Goal mapping examples (Master Document Map #9, DISPLAY), verbatim. */
export const GOAL_MAPPING_BODY = [
  p('This section explains how to confidently and ethically connect participant supports to their stated goals in a way that aligns with NDIS legislative requirements, particularly Section 34 of the NDIS Act. It is written to support independent workers, auditors, and participants using the TMG Framework. This process reflects relational discipline, ensures legal defensibility, and promotes participant-centred practice.'),
  h2('1. Relational Discipline Meets ‘Reasonable and Necessary’'),
  p('Relational Discipline is the foundation of this framework. It recognises that connection, trust, and emotional safety are not just desirable - they are essential to support effectiveness. However, under the NDIS, supports must also be ‘reasonable and necessary’ under Section 34 of the Act. This means that supports must:'),
  list([
    "Be related to the participant's disability",
    'Not be more appropriately funded by another service',
    'Represent value for money',
    'Be likely to benefit the participant',
    'Support the pursuit of goals',
  ]),
  p("Workers often worry that relational supports - such as providing stability, encouragement, or helping a participant manage emotional dysregulation - may not `count'. But these are often *the most necessary* for a person to access other supports or build capacity. Emotional regulation, social engagement, and psychological safety are functional capacities."),
  h2('2. Functional Capacity Domains'),
  p("NDIS recognises six functional capacity domains. Any support linked to these areas, when clearly connected to the participant's disability and goals, is valid. They are:"),
  list(['Mobility', 'Communication', 'Social interaction', 'Learning', 'Self-care', 'Self-management']),
  p('Relational supports (like helping someone manage anxiety when leaving the house) directly impact multiple domains, especially social interaction and self-management.'),
  h2('3. Intake → Goal → Support Examples'),
  p('Example 1'),
  p('Goal: "Improve my mental and physical health."'),
  p('Support: Weekly walks with a support worker who understands trauma-informed care.'),
  p('Justification: Linked to mobility, self-care, and social interaction. May also include meal prep or healthy shopping if nutrition is affected by medication or mental health.'),
  p("Evidence Phrase: \"Support builds participant's capacity to improve wellbeing through structured, safe engagement that promotes emotional regulation and healthy routines.\""),
  p('Example 2'),
  p('Goal: "Have a sense of purpose and connection."'),
  p('Support: Regular home visits with a relationally trained worker to explore strengths and support the creation of a blog or small project.'),
  p('Justification: Linked to social interaction, learning, and self-management. May reduce isolation and build confidence to access the community.'),
  p('Evidence Phrase: "Support enables participant to explore purposeful activity aligned with their goals, and reduces functional impact of isolation or trauma symptoms."'),
  h2('4. Legal Notes for Workers'),
  p('NDIS does not require full clinical justification in notes, but does require that supports are clearly linked to functional impact and goals. Always:'),
  list(['Refer to participant goals', 'Use the intake form as a dynamic document', 'Describe outcomes in terms of functional benefit', 'Use respectful, strength-based language']),
  h2('Additional Examples to Expand Understanding'),
  p('Goal: "Increase social and community participation."'),
  p('Support: Participant engages in a weekly online peer group facilitated by a worker using trauma-informed relational practices.'),
  p('Justification: Linked to communication and social interaction domains. Supports connection and reduces social isolation, especially where in-person participation is not yet accessible.'),
  p('Evidence Phrase: "Digital social support enables progressive engagement with community, reducing psychological barriers and fostering inclusion."'),
  p('Goal: "Build my capacity to start a small business."'),
  p('Support: Worker assists participant to develop a content calendar, build routines, and explore basic digital skills necessary for a micro-enterprise.'),
  p('Justification: Linked to learning, communication, and self-management domains. Addresses purpose, economic participation, and self-direction.'),
  p("Evidence Phrase: \"Support focuses on capacity building through structured, goal-oriented engagement aligned with the participant's long-term aspirations.\""),
  p('Goal: "Improve day-to-day functioning and independence."'),
  p('Support: Support worker assists with domestic activities like cleaning and meal prep to reduce overwhelm and build routines.'),
  p('Justification: Linked to self-care and self-management. Ensures energy and focus are available for therapy, appointments, and goal setting.'),
  p('Evidence Phrase: "Domestic assistance ensures basic needs are met and participant can actively engage with broader capacity-building activities."'),
  p('Goal: "Establish a routine and manage emotional regulation."'),
  p('Support: Relational worker supports participant in developing and maintaining a weekly structure, including mindfulness or check-in sessions.'),
  p('Justification: Directly related to social interaction and self-management. Foundational for engaging with other supports safely.'),
  p('Evidence Phrase: "Structured emotional support reduces behavioural volatility and enables continuity in therapeutic and capacity-building goals."'),
];

/** AI Governance Register v1.0, verbatim. */
export const AI_GOVERNANCE_BODY = [
  h2('Purpose'),
  p('This register provides a consolidated governance overview of AI systems, AI-assisted workflows, and AI governance controls operating within the TMG180 ecosystem.'),
  p('The purpose of this register is to:'),
  list(['support transparency;', 'support governance oversight;', 'support audit readiness;', 'support implementation consistency;', 'support responsible AI use;', 'and provide a central reference point for AI governance across the ecosystem.']),
  h2('AI Governance Principles'),
  p('TMG180 utilises AI as assistive infrastructure.'),
  p('AI systems exist to support:'),
  list(['workflow accessibility;', 'documentation support;', 'longitudinal understanding;', 'governance consistency;', 'operational sustainability;', 'participant-centred implementation;', 'and relational continuity.']),
  p('AI systems do not replace:'),
  list(['participant autonomy;', 'human judgement;', 'professional responsibilities;', 'safeguarding obligations;', 'governance oversight;', 'or legal accountability.']),
  h2('AI Governance Controls'),
  p('Active: Human Oversight Required · AI Subordinate to Human Decision-Making · Participant-Centred Design · Transparency Requirements · Governance Alignment Requirements · Safeguarding Alignment Requirements · Documentation Standards Alignment · Privacy Compliance Requirements · Platform Governance Oversight · Review and Monitoring Requirements.'),
  h2('AI Workflow Functions'),
  p('AI may be utilised to support:'),
  list(['workflow guidance;', 'documentation assistance;', 'longitudinal summarisation;', 'operational navigation;', 'governance interpretation;', 'educational resources;', 'and implementation support.']),
  h2('AI Restrictions'),
  p('AI must not:'),
  list(['replace safeguarding responsibilities;', 'make autonomous governance decisions;', 'remove participant choice and control;', 'replace professional judgement;', 'create hidden decision-making processes;', 'perform regulatory functions;', 'or operate without governance oversight.']),
  h2('Governance Principle'),
  p('AI exists to strengthen human-centred support systems.'),
  p('AI should reduce fragmentation, administrative burden, and operational complexity while preserving participant autonomy, worker sustainability, safeguarding, transparency, and governance integrity.'),
  h2('Governance Note'),
  p('All AI systems operating within TMG180 remain subject to:'),
  list(['human oversight;', 'governance review;', 'safeguarding obligations;', 'privacy requirements;', 'and ongoing evaluation.']),
];

/** TMG180 Governance Architecture v1.0, verbatim. */
export const GOVERNANCE_ARCHITECTURE_BODY = [
  h2('Purpose'),
  p('This document defines the structure of the TMG180 governance suite and identifies the purpose of each core governance document.'),
  p('The purpose of this architecture is to:'),
  list(['provide a clear governance framework structure;', 'reduce document duplication;', 'support audit readiness;', 'support implementation continuity;', 'support future document management;', 'and provide a central reference point for the TMG180 ecosystem.']),
  h2('Governance Suite Structure'),
  p('Volume 1 – TMG180 Foundational Framework'),
  p('Purpose: Defines the philosophy, principles, purpose, and conceptual foundations of the TMG180 ecosystem.'),
  p('Primary Audience: Participants, workers, stakeholders, governance reviewers.'),
  p('Volume 2 – Governance & Operations Manual'),
  p('Purpose: Defines mandatory governance controls, policies, operational requirements, safeguarding, privacy, complaints, incident management, and accountability structures.'),
  p('Primary Audience: Workers, auditors, governance reviewers, compliance stakeholders.'),
  p('Volume 3 – Development & Integration Report'),
  p('Purpose: Documents the development journey, governance integration process, legislative alignment methodology, and ecosystem design rationale.'),
  p('Primary Audience: Auditors, legal reviewers, governance reviewers, future implementation teams.'),
  p('Volume 4 – Relational Governance Practice Standards Manual'),
  p('Purpose: Defines relational governance standards, best-practice guidance, ethical frameworks, and worker practice expectations.'),
  p('Primary Audience: Workers, governance reviewers, training and onboarding functions.'),
  p('Volume 5 – NDIS Interpretation & Knowledge Library'),
  p('Purpose: Provides educational resources, support interpretation guidance, participant-centred practice information, and operational learning materials.'),
  p('Primary Audience: Workers, participants, support professionals.'),
  p('Volume 6 – Platform & Technical Governance Manual'),
  p('Purpose: Defines platform operations, technical governance, platform boundaries, workflow architecture, permissions, and digital infrastructure.'),
  p('Primary Audience: Developers, governance reviewers, implementation teams.'),
  h2('Governance Principle'),
  p('The TMG180 governance suite is designed to ensure that governance, safeguarding, participant autonomy, worker sustainability, relational practice, legislative alignment, and digital infrastructure remain integrated within a coherent operational ecosystem.'),
];
